### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by jovrtn** [zotero/zotero-schema#3]
Hello, looking to build support for this schema into an app but wondering if this is still maintained/updated. Thanks!

**Comment by dstillman** [comment]
Yes? Not sure why you'd think otherwise — the last commit was [a month ago](https://github.com/zotero/zotero-schema/commit/4277955e5927bc31b668367e657b87dd30e661dc), and this submodule is [included in the desktop app](https://github.com/zotero/zotero/tree/master/resource/schema).
